version: '3.7'

services:
  geoserver:
    image: maxdragonheart/geoserver:latest
    environment:
        GS_VERSION: ${GS_VERSION}
        GS_DEMO_DATA: ${GS_DEMO_DATA}
        GS_HTTP_PORT: ${GS_HTTP_PORT}
        GS_INITIAL_MEMORY: ${GS_INITIAL_MEMORY}
        GS_MAXIMUM_MEMORY: ${GS_MAXIMUM_MEMORY}
        TOMCAT_MAJOR: ${TOMCAT_MAJOR}
        TOMCAT_MINOR: ${TOMCAT_MINOR}
        TOMCAT_PATCH: ${TOMCAT_PATCH}
    container_name: test_geoserver
    restart: always
    ports:
    - "${GS_HTTP_PORT}:8080"
    volumes:
    - geoserver:/opt/tomcat/webapps/geoserver
    networks:
      - test

  python-api:
    image: maxdragonheart/${PROJECT_NAME}
    build:
      context: ./pythonapi
      dockerfile: Dockerfile
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DOMAIN: ${DOMAIN}
      WORKSPACE: ${WORKSPACE}
      SERVICE_VERSION: ${SERVICE_VERSION}
      LAYER_NAME: ${LAYER_NAME}
    container_name: test_pythonapi
    restart: always
    ports:
    - "${PYTHON_API_PORT}:8301"
    depends_on:
      - geoserver
    networks:
      - test

volumes:
  geoserver:

networks:
  test:
    driver: bridge