version: '3.7'

services:
#  geoserver:
#    image: maxdragonheart/geoserver:latest
#    environment:
#        GS_VERSION: ${GS_VERSION}
#        GS_DEMO_DATA: ${GS_DEMO_DATA}
#        GS_HTTP_PORT: ${GS_HTTP_PORT}
#        GS_INITIAL_MEMORY: ${GS_INITIAL_MEMORY}
#        GS_MAXIMUM_MEMORY: ${GS_MAXIMUM_MEMORY}
#        TOMCAT_MAJOR: ${TOMCAT_MAJOR}
#        TOMCAT_MINOR: ${TOMCAT_MINOR}
#        TOMCAT_PATCH: ${TOMCAT_PATCH}
#    container_name: test-geoserver
#    restart: always
#    ports:
#    - ${GS_HTTP_PORT}:8080
#    volumes:
#    - geoserver:/opt/tomcat/webapps/geoserver
#    networks:
#      - test

  pythonapi:
    image: maxdragonheart/${PROJECT_NAME}
    build:
      context: ./pythonapi
      dockerfile: Dockerfile
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DOMAIN: ${DOMAIN}
      WORKSPACE: ${WORKSPACE}
      SERVICE_VERSION: ${SERVICE_VERSION}
      LAYER_NAME: ${LAYER_NAME}
    container_name: test-pythonapi
    restart: always
    ports:
    - ${PYTHON_API_PORT}:5000
#    depends_on:
#      - geoserver
    networks:
      - test

#  nginx:
#    image: maxdragonheart/nginx
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    container_name: test-nginx
#    volumes:
#      - nginx-logs:/var/log/nginx
#    ports:
#      - 80:80
#      - 443:443
#    depends_on:
#      - pythonapi
#    networks:
#      - test
#
#volumes:
#  geoserver:
#  nginx-logs:

networks:
  test:
    driver: bridge
