[tool.poetry]
name = "pythonapi"
version = "0.0.1"
description = ""
authors = ["MaxDragonheart <massimilianomoraca@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
urllib3 = "^1.26.9"
OWSLib = "^0.25.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
